#pragma once
#include <cstdint>

enum class OpCode : uint8_t {
    OP_CONSTANT,
    OP_NIL,
    OP_TRUE,
    OP_FALSE,
    OP_DEFINE_GLOBAL,
    OP_DEFINE_GLOBAL_TYPED,
    OP_CHECK_LOCAL_TYPE,
    OP_GET_GLOBAL,
    OP_SET_GLOBAL,
    OP_GET_LOCAL,
    OP_SET_LOCAL,
    OP_CALL,
    OP_BUILD_ARRAY,
    OP_BUILD_MAP,
    OP_GET_INDEX,
    OP_SET_INDEX,
    OP_GRAB,
    OP_EQUAL,
    OP_GREATER,
    OP_LESS,
    OP_ADD,
    OP_SUBTRACT,
    OP_MULTIPLY,
    OP_DIVIDE,
    OP_MODULO,
    OP_POWER,
    OP_NOT,
    OP_JUMP,
    OP_JUMP_IF_FALSE,
    OP_LOOP,
    OP_PRINT,
    OP_POP,
    OP_DUP,
    OP_DUP_2,
    OP_RETURN
};
